// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	dbStatus: () => typedError<DbStatus, string>(__TAURI_INVOKE("db_status")),
	login: (username: string, password: string) => typedError<LoginOk, string>(__TAURI_INVOKE("login", { username, password })),
	logout: () => typedError<null, string>(__TAURI_INVOKE("logout")),
	sessionState: () => typedError<{
	id: number,
	username: string,
	must_change_password: boolean,
	is_super_admin: boolean,
	roles: string[],
	permissions: string[],
} | null, string>(__TAURI_INVOKE("session_state")),
	changePassword: (currentPassword: string, newPassword: string) => typedError<null, string>(__TAURI_INVOKE("change_password", { currentPassword, newPassword })),
	requestPasswordReset: (email: string) => typedError<string | null, string>(__TAURI_INVOKE("request_password_reset", { email })),
	resetPassword: (token: string, newPassword: string) => typedError<null, string>(__TAURI_INVOKE("reset_password", { token, newPassword })),
	mfaChallenge: (userId: number, code: string) => typedError<LoginOk, string>(__TAURI_INVOKE("mfa_challenge", { userId, code })),
	mfaSetup: () => typedError<MfaSetup, string>(__TAURI_INVOKE("mfa_setup")),
	mfaEnable: (code: string) => typedError<null, string>(__TAURI_INVOKE("mfa_enable", { code })),
	mfaDisable: (password: string) => typedError<null, string>(__TAURI_INVOKE("mfa_disable", { password })),
	listRoles: () => typedError<Role[], string>(__TAURI_INVOKE("list_roles")),
	createRole: (slug: string, name: string, description: string | null) => typedError<number, string>(__TAURI_INVOKE("create_role", { slug, name, description })),
	updateRole: (roleId: number, name: string, description: string | null) => typedError<null, string>(__TAURI_INVOKE("update_role", { roleId, name, description })),
	deleteRole: (roleId: number) => typedError<null, string>(__TAURI_INVOKE("delete_role", { roleId })),
	listPermissions: () => typedError<Permission[], string>(__TAURI_INVOKE("list_permissions")),
	rolePermissionIds: (roleId: number) => typedError<number[], string>(__TAURI_INVOKE("role_permission_ids", { roleId })),
	syncRolePermissions: (roleId: number, permissionIds: number[]) => typedError<null, string>(__TAURI_INVOKE("sync_role_permissions", { roleId, permissionIds })),
	listUsers: () => typedError<UserRow[], string>(__TAURI_INVOKE("list_users")),
	userRoleIds: (userId: number) => typedError<number[], string>(__TAURI_INVOKE("user_role_ids", { userId })),
	syncUserRoles: (userId: number, roleIds: number[]) => typedError<null, string>(__TAURI_INVOKE("sync_user_roles", { userId, roleIds })),
	toggleUserStatus: (userId: number, status: string) => typedError<null, string>(__TAURI_INVOKE("toggle_user_status", { userId, status })),
	adminResetPassword: (userId: number, newPassword: string) => typedError<null, string>(__TAURI_INVOKE("admin_reset_password", { userId, newPassword })),
	auditList: (module: string | null, limit: number | null) => typedError<AuditEntry[], string>(__TAURI_INVOKE("audit_list", { module, limit })),
	backupNow: () => typedError<string, string>(__TAURI_INVOKE("backup_now")),
	backupList: () => typedError<BackupFile[], string>(__TAURI_INVOKE("backup_list")),
	backupRestore: (name: string) => typedError<null, string>(__TAURI_INVOKE("backup_restore", { name })),
	getSettings: () => typedError<Setting[], string>(__TAURI_INVOKE("get_settings")),
	saveSettings: (items: ([string, string])[]) => typedError<null, string>(__TAURI_INVOKE("save_settings", { items })),
	getCompany: () => typedError<{
	id: number,
	code: string,
	name: string,
	legal_name: string | null,
	address: string | null,
	city: string | null,
	province: string | null,
	postal_code: string | null,
	phone: string | null,
	email: string | null,
	npwp: string | null,
	established_date: string | null,
} | null, string>(__TAURI_INVOKE("get_company")),
	saveCompany: (input: CompanyInput) => typedError<null, string>(__TAURI_INVOKE("save_company", { input })),
	orgEntities: () => typedError<EntityMeta[], string>(__TAURI_INVOKE("org_entities")),
	orgList: (slug: string, search: string, page: number, perPage: number) => typedError<OrgPage, string>(__TAURI_INVOKE("org_list", { slug, search, page, perPage })),
	orgGet: (slug: string, id: number) => typedError<{ [key in string]: string } | null, string>(__TAURI_INVOKE("org_get", { slug, id })),
	orgOptions: (slug: string, field: string) => typedError<Opt[], string>(__TAURI_INVOKE("org_options", { slug, field })),
	orgSave: (slug: string, id: number | null, values: { [key in string]: string }) => typedError<number, string>(__TAURI_INVOKE("org_save", { slug, id, values })),
	orgDelete: (slug: string, id: number) => typedError<null, string>(__TAURI_INVOKE("org_delete", { slug, id })),
	orgChart: () => typedError<CompanyNode[], string>(__TAURI_INVOKE("org_chart")),
	listWorkflows: () => typedError<Workflow[], string>(__TAURI_INVOKE("list_workflows")),
	addWorkflowStep: (workflowId: number, approverType: string, roleId: number | null, userId: number | null) => typedError<number, string>(__TAURI_INVOKE("add_workflow_step", { workflowId, approverType, roleId, userId })),
	removeWorkflowStep: (stepId: number) => typedError<null, string>(__TAURI_INVOKE("remove_workflow_step", { stepId })),
	employeeList: (search: string, filters: EmployeeFilter, page: number, perPage: number) => typedError<EmployeePage, string>(__TAURI_INVOKE("employee_list", { search, filters, page, perPage })),
	employeeDetail: (id: number) => typedError<{
	id: number,
	employee_number: string,
	nik: string | null,
	first_name: string,
	last_name: string | null,
	photo: string | null,
	birth_place: string | null,
	birth_date: string | null,
	gender: string,
	religion: string | null,
	marital_status: string,
	phone: string | null,
	personal_email: string | null,
	company_id: number,
	branch_id: number | null,
	department_id: number | null,
	division_id: number | null,
	section_id: number | null,
	position_id: number | null,
	job_level_id: number | null,
	job_grade_id: number | null,
	work_location_id: number | null,
	cost_center_id: number | null,
	supervisor_id: number | null,
	manager_id: number | null,
	join_date: string,
	appointment_date: string | null,
	resign_date: string | null,
	employment_status: string,
	employment_type: string,
	bank_name: string | null,
	bank_account_number: string | null,
	bank_account_holder: string | null,
	npwp: string | null,
	ptkp_status: string | null,
	bpjs_health_number: string | null,
	bpjs_employment_number: string | null,
	company_name: string | null,
	branch_name: string | null,
	department_name: string | null,
	division_name: string | null,
	section_name: string | null,
	position_name: string | null,
	job_level_name: string | null,
	job_grade_name: string | null,
	work_location_name: string | null,
	cost_center_name: string | null,
	supervisor_name: string | null,
	manager_name: string | null,
} | null, string>(__TAURI_INVOKE("employee_detail", { id })),
	employeeDropdowns: () => typedError<Dropdowns, string>(__TAURI_INVOKE("employee_dropdowns")),
	employeeCreate: (input: EmployeeInput, photo: {
	name: string,
	mime: string,
	bytes: number[],
} | null) => typedError<number, string>(__TAURI_INVOKE("employee_create", { input, photo })),
	employeeUpdate: (id: number, input: EmployeeInput, resignDate: string | null, photo: {
	name: string,
	mime: string,
	bytes: number[],
} | null) => typedError<null, string>(__TAURI_INVOKE("employee_update", { id, input, resignDate, photo })),
	employeeDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("employee_delete", { id })),
	employeeChildTypes: () => typedError<ChildMeta[], string>(__TAURI_INVOKE("employee_child_types")),
	employeeChildList: (child: string, employeeId: number) => typedError<{ [key in string]: string }[], string>(__TAURI_INVOKE("employee_child_list", { child, employeeId })),
	employeeChildSave: (child: string, employeeId: number, id: number | null, values: { [key in string]: string }) => typedError<number, string>(__TAURI_INVOKE("employee_child_save", { child, employeeId, id, values })),
	employeeChildDelete: (child: string, employeeId: number, id: number) => typedError<null, string>(__TAURI_INVOKE("employee_child_delete", { child, employeeId, id })),
	contractExpiring: (days: number) => typedError<ContractAlert[], string>(__TAURI_INVOKE("contract_expiring", { days })),
	employeeAddresses: (employeeId: number) => typedError<Addresses, string>(__TAURI_INVOKE("employee_addresses", { employeeId })),
	employeeAddressSave: (employeeId: number, addressType: string, values: { [key in string]: string }) => typedError<null, string>(__TAURI_INVOKE("employee_address_save", { employeeId, addressType, values })),
	employeeDocuments: (employeeId: number) => typedError<Document[], string>(__TAURI_INVOKE("employee_documents", { employeeId })),
	employeeDocumentUpload: (employeeId: number, category: string, name: string, expiryDate: string | null, file: FileUpload) => typedError<number, string>(__TAURI_INVOKE("employee_document_upload", { employeeId, category, name, expiryDate, file })),
	employeeDocumentBytes: (employeeId: number, id: number) => typedError<DocumentBytes, string>(__TAURI_INVOKE("employee_document_bytes", { employeeId, id })),
	employeeDocumentDelete: (employeeId: number, id: number) => typedError<null, string>(__TAURI_INVOKE("employee_document_delete", { employeeId, id })),
	employeeSalaryCurrent: (employeeId: number) => typedError<{
	id: number,
	basic_salary: number | null,
	effective_date: string,
	is_active: boolean,
} | null, string>(__TAURI_INVOKE("employee_salary_current", { employeeId })),
	employeeSalaryHistory: (employeeId: number) => typedError<SalaryRow[], string>(__TAURI_INVOKE("employee_salary_history", { employeeId })),
	employeeSalaryComponents: (salaryId: number) => typedError<SalaryComponentRow[], string>(__TAURI_INVOKE("employee_salary_components", { salaryId })),
	employeeAvailableComponents: () => typedError<SalaryComponentRow[], string>(__TAURI_INVOKE("employee_available_components")),
	employeeSetSalary: (employeeId: number, basicSalary: number | null, effectiveDate: string, components: ([number, number | null])[]) => typedError<number, string>(__TAURI_INVOKE("employee_set_salary", { employeeId, basicSalary, effectiveDate, components })),
	shiftList: () => typedError<Shift[], string>(__TAURI_INVOKE("shift_list")),
	shiftSave: (id: number | null, input: ShiftInput) => typedError<number, string>(__TAURI_INVOKE("shift_save", { id, input })),
	shiftDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("shift_delete", { id })),
	scheduleList: () => typedError<Schedule[], string>(__TAURI_INVOKE("schedule_list")),
	scheduleSave: (id: number | null, input: ScheduleInput) => typedError<number, string>(__TAURI_INVOKE("schedule_save", { id, input })),
	scheduleSaveDays: (scheduleId: number, days: ([number, number | null, boolean])[]) => typedError<null, string>(__TAURI_INVOKE("schedule_save_days", { scheduleId, days })),
	scheduleDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("schedule_delete", { id })),
	assignmentList: () => typedError<Assignment[], string>(__TAURI_INVOKE("assignment_list")),
	assignmentSave: (id: number | null, input: AssignmentInput) => typedError<number, string>(__TAURI_INVOKE("assignment_save", { id, input })),
	assignmentDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("assignment_delete", { id })),
	holidayList: () => typedError<Holiday[], string>(__TAURI_INVOKE("holiday_list")),
	holidaySave: (id: number | null, input: HolidayInput) => typedError<number, string>(__TAURI_INVOKE("holiday_save", { id, input })),
	holidayDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("holiday_delete", { id })),
	attendanceToday: () => typedError<{
	id: number,
	employee_id: number,
	date: string,
	clock_in: string | null,
	clock_out: string | null,
	status: string,
	late_minutes: number,
	early_minutes: number,
	work_minutes: number,
	notes: string | null,
	shift_id: number | null,
} | null, string>(__TAURI_INVOKE("attendance_today")),
	attendanceClockIn: (lat: number | null, lng: number | null) => typedError<ClockResult, string>(__TAURI_INVOKE("attendance_clock_in", { lat, lng })),
	attendanceClockOut: (lat: number | null, lng: number | null) => typedError<ClockResult, string>(__TAURI_INVOKE("attendance_clock_out", { lat, lng })),
	attendanceHistory: (month: string) => typedError<Attendance[], string>(__TAURI_INVOKE("attendance_history", { month })),
	attendanceRecap: (date: string, search: string) => typedError<RecapRow[], string>(__TAURI_INVOKE("attendance_recap", { date, search })),
	attendanceManual: (input: ManualInput) => typedError<number, string>(__TAURI_INVOKE("attendance_manual", { input })),
	attendanceMyCorrections: () => typedError<Correction[], string>(__TAURI_INVOKE("attendance_my_corrections")),
	attendancePendingCorrections: () => typedError<Correction[], string>(__TAURI_INVOKE("attendance_pending_corrections")),
	attendanceRequestCorrection: (input: CorrectionInput) => typedError<number, string>(__TAURI_INVOKE("attendance_request_correction", { input })),
	attendanceDecideCorrection: (id: number, decision: string, notes: string | null) => typedError<null, string>(__TAURI_INVOKE("attendance_decide_correction", { id, decision, notes })),
	leaveBalances: (year: number) => typedError<Balance[], string>(__TAURI_INVOKE("leave_balances", { year })),
	leaveTypes: () => typedError<LeaveType[], string>(__TAURI_INVOKE("leave_types")),
	leaveTypeSave: (id: number | null, input: LeaveTypeInput) => typedError<number, string>(__TAURI_INVOKE("leave_type_save", { id, input })),
	leaveTypeDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("leave_type_delete", { id })),
	leaveMy: () => typedError<LeaveRequest[], string>(__TAURI_INVOKE("leave_my")),
	leavePending: () => typedError<LeaveRequest[], string>(__TAURI_INVOKE("leave_pending")),
	leaveAll: () => typedError<LeaveRequest[], string>(__TAURI_INVOKE("leave_all")),
	leaveCreate: (input: LeaveCreate) => typedError<number, string>(__TAURI_INVOKE("leave_create", { input })),
	leaveDecide: (id: number, decision: string, notes: string | null) => typedError<null, string>(__TAURI_INVOKE("leave_decide", { id, decision, notes })),
	leaveCancel: (id: number) => typedError<null, string>(__TAURI_INVOKE("leave_cancel", { id })),
	leaveCalendar: (month: string) => typedError<CalendarDay[], string>(__TAURI_INVOKE("leave_calendar", { month })),
	overtimeMy: () => typedError<Overtime[], string>(__TAURI_INVOKE("overtime_my")),
	overtimePending: () => typedError<Overtime[], string>(__TAURI_INVOKE("overtime_pending")),
	overtimeAll: () => typedError<Overtime[], string>(__TAURI_INVOKE("overtime_all")),
	overtimeCreate: (input: OvertimeCreate) => typedError<number, string>(__TAURI_INVOKE("overtime_create", { input })),
	overtimeDecide: (id: number, decision: string, notes: string | null) => typedError<null, string>(__TAURI_INVOKE("overtime_decide", { id, decision, notes })),
	permissionTypes: () => typedError<PermissionType[], string>(__TAURI_INVOKE("permission_types")),
	permissionMy: () => typedError<PermissionRequest[], string>(__TAURI_INVOKE("permission_my")),
	permissionPending: () => typedError<PermissionRequest[], string>(__TAURI_INVOKE("permission_pending")),
	permissionAll: () => typedError<PermissionRequest[], string>(__TAURI_INVOKE("permission_all")),
	permissionCreate: (input: PermissionCreate) => typedError<number, string>(__TAURI_INVOKE("permission_create", { input })),
	permissionDecide: (id: number, decision: string) => typedError<null, string>(__TAURI_INVOKE("permission_decide", { id, decision })),
	payrollPeriods: () => typedError<Period[], string>(__TAURI_INVOKE("payroll_periods")),
	payrollPeriodCreate: (input: PeriodInput) => typedError<number, string>(__TAURI_INVOKE("payroll_period_create", { input })),
	payrollRows: (periodId: number) => typedError<PayrollRow[], string>(__TAURI_INVOKE("payroll_rows", { periodId })),
	payrollDetail: (id: number) => typedError<{
	id: number,
	employee_id: number,
	employee_number: string,
	name: string,
	department_name: string | null,
	position_name: string | null,
	period_name: string,
	start_date: string,
	end_date: string,
	basic_salary: number | null,
	total_income: number | null,
	total_deduction: number | null,
	net_salary: number | null,
	status: string,
	lines: PayrollLine[],
} | null, string>(__TAURI_INVOKE("payroll_detail", { id })),
	payrollGenerate: (periodId: number) => typedError<null, string>(__TAURI_INVOKE("payroll_generate", { periodId })),
	payrollApprove: (periodId: number) => typedError<null, string>(__TAURI_INVOKE("payroll_approve", { periodId })),
	payrollPay: (periodId: number) => typedError<null, string>(__TAURI_INVOKE("payroll_pay", { periodId })),
	payrollLock: (periodId: number) => typedError<null, string>(__TAURI_INVOKE("payroll_lock", { periodId })),
	payrollMySlips: () => typedError<PayslipInfo[], string>(__TAURI_INVOKE("payroll_my_slips")),
	payrollPayslipRender: (payrollId: number) => typedError<string, string>(__TAURI_INVOKE("payroll_payslip_render", { payrollId })),
	payrollPayslipFile: (payrollId: number) => typedError<PayslipFile, string>(__TAURI_INVOKE("payroll_payslip_file", { payrollId })),
	payrollComponents: () => typedError<Component[], string>(__TAURI_INVOKE("payroll_components")),
	payrollComponentSave: (id: number | null, input: ComponentInput) => typedError<number, string>(__TAURI_INVOKE("payroll_component_save", { id, input })),
	payrollComponentDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("payroll_component_delete", { id })),
	payrollDeductions: (pendingOnly: boolean) => typedError<Deduction[], string>(__TAURI_INVOKE("payroll_deductions", { pendingOnly })),
	payrollDeductionSave: (id: number | null, input: DeductionInput) => typedError<number, string>(__TAURI_INVOKE("payroll_deduction_save", { id, input })),
	payrollDeductionDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("payroll_deduction_delete", { id })),
	vacancyList: () => typedError<Vacancy[], string>(__TAURI_INVOKE("vacancy_list")),
	vacancyGet: (id: number) => typedError<{
	id: number,
	title: string,
	department_id: number | null,
	department_name: string | null,
	position_id: number | null,
	position_name: string | null,
	employment_type: string,
	description: string | null,
	requirements: string | null,
	quota: number,
	status: string,
	posted_date: string | null,
	closing_date: string | null,
	candidate_count: number,
} | null, string>(__TAURI_INVOKE("vacancy_get", { id })),
	vacancySave: (id: number | null, input: VacancyInput) => typedError<number, string>(__TAURI_INVOKE("vacancy_save", { id, input })),
	vacancyDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("vacancy_delete", { id })),
	candidatesByVacancy: (vacancyId: number) => typedError<CandidateRow[], string>(__TAURI_INVOKE("candidates_by_vacancy", { vacancyId })),
	candidateDetail: (id: number) => typedError<{
	id: number,
	vacancy_id: number,
	vacancy_title: string,
	full_name: string,
	email: string | null,
	phone: string | null,
	birth_date: string | null,
	gender: string | null,
	address: string | null,
	cv_path: string | null,
	source: string | null,
	stage: string,
	rating: number | null,
	notes: string | null,
	employee_id: number | null,
	documents: CandidateDoc[],
	interviews: Interview[],
	assessments: Assessment[],
	stage_history: StageEvent[],
} | null, string>(__TAURI_INVOKE("candidate_detail", { id })),
	candidateCreate: (vacancyId: number, input: CandidateInput, cv: {
	name: string,
	mime: string,
	bytes: number[],
} | null) => typedError<number, string>(__TAURI_INVOKE("candidate_create", { vacancyId, input, cv })),
	candidateDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("candidate_delete", { id })),
	candidateStage: (id: number, stage: string, notes: string | null) => typedError<null, string>(__TAURI_INVOKE("candidate_stage", { id, stage, notes })),
	interviewAdd: (candidateId: number, input: InterviewInput) => typedError<number, string>(__TAURI_INVOKE("interview_add", { candidateId, input })),
	interviewDecide: (id: number, result: string, notes: string | null) => typedError<null, string>(__TAURI_INVOKE("interview_decide", { id, result, notes })),
	assessmentAdd: (candidateId: number, input: AssessmentInput) => typedError<number, string>(__TAURI_INVOKE("assessment_add", { candidateId, input })),
	candidateHire: (id: number, joinDate: string | null) => typedError<number, string>(__TAURI_INVOKE("candidate_hire", { id, joinDate })),
	candidateCv: (candidateId: number, id: number) => typedError<DocumentBytes, string>(__TAURI_INVOKE("candidate_cv", { candidateId, id })),
	onboardingList: () => typedError<Onboarding[], string>(__TAURI_INVOKE("onboarding_list")),
	onboardingGet: (id: number) => typedError<{
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	start_date: string,
	status: string,
	progress_percent: number,
	tasks: OnboardingTask[],
} | null, string>(__TAURI_INVOKE("onboarding_get", { id })),
	onboardingMine: () => typedError<{
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	start_date: string,
	status: string,
	progress_percent: number,
	tasks: OnboardingTask[],
} | null, string>(__TAURI_INVOKE("onboarding_mine")),
	onboardingToggle: (taskId: number, completed: boolean) => typedError<[number, string], string>(__TAURI_INVOKE("onboarding_toggle", { taskId, completed })),
	offboardingList: () => typedError<OffboardingRow[], string>(__TAURI_INVOKE("offboarding_list")),
	offboardingMy: () => typedError<OffboardingRow[], string>(__TAURI_INVOKE("offboarding_my")),
	offboardingGet: (id: number) => typedError<{
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	supervisor_id: number | null,
	resignation_date: string,
	last_working_date: string,
	reason: string | null,
	status: string,
	current_step: number,
	exit_interview: ExitInterview | null,
	clearance_items: ClearanceItem[],
} | null, string>(__TAURI_INVOKE("offboarding_get", { id })),
	offboardingCreate: (input: OffboardingCreate) => typedError<number, string>(__TAURI_INVOKE("offboarding_create", { input })),
	offboardingDecide: (id: number, action: string) => typedError<string, string>(__TAURI_INVOKE("offboarding_decide", { id, action })),
	offboardingExitSave: (id: number, input: ExitInterviewInput) => typedError<null, string>(__TAURI_INVOKE("offboarding_exit_save", { id, input })),
	offboardingClearance: (itemId: number, cleared: boolean, notes: string | null) => typedError<null, string>(__TAURI_INVOKE("offboarding_clearance", { itemId, cleared, notes })),
	performancePeriods: () => typedError<PerfPeriod[], string>(__TAURI_INVOKE("performance_periods")),
	performancePeriodSave: (id: number | null, input: PerfPeriodInput) => typedError<number, string>(__TAURI_INVOKE("performance_period_save", { id, input })),
	performancePeriodDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("performance_period_delete", { id })),
	performanceKpis: () => typedError<Kpi[], string>(__TAURI_INVOKE("performance_kpis")),
	performanceKpiSave: (id: number | null, input: KpiInput) => typedError<number, string>(__TAURI_INVOKE("performance_kpi_save", { id, input })),
	performanceKpiDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("performance_kpi_delete", { id })),
	performanceReviews: (periodId: number) => typedError<ReviewRow[], string>(__TAURI_INVOKE("performance_reviews", { periodId })),
	performanceMyReviews: () => typedError<ReviewRow[], string>(__TAURI_INVOKE("performance_my_reviews")),
	performanceReviewDetail: (id: number) => typedError<{
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	period_name: string,
	status: string,
	self_score: number | null,
	supervisor_score: number | null,
	manager_score: number | null,
	hr_score: number | null,
	final_score: number | null,
	final_rating: number | null,
	kpis: ReviewKpi[],
	scores: ReviewScore[],
} | null, string>(__TAURI_INVOKE("performance_review_detail", { id })),
	performanceEnsureReview: (periodId: number, employeeId: number) => typedError<number, string>(__TAURI_INVOKE("performance_ensure_review", { periodId, employeeId })),
	performanceAssignKpi: (periodId: number, employeeId: number, kpiId: number, target: number | null, weight: number | null) => typedError<number, string>(__TAURI_INVOKE("performance_assign_kpi", { periodId, employeeId, kpiId, target, weight })),
	performanceSubmitActual: (employeeKpiId: number, actual: number | null) => typedError<number | null, string>(__TAURI_INVOKE("performance_submit_actual", { employeeKpiId, actual })),
	performanceSubmitReview: (reviewId: number, role: string, score: number | null, comments: string | null) => typedError<null, string>(__TAURI_INVOKE("performance_submit_review", { reviewId, role, score, comments })),
	trainingList: () => typedError<Training[], string>(__TAURI_INVOKE("training_list")),
	trainingParticipants: (trainingId: number) => typedError<Participant[], string>(__TAURI_INVOKE("training_participants", { trainingId })),
	trainingSave: (id: number | null, input: TrainingInput) => typedError<number, string>(__TAURI_INVOKE("training_save", { id, input })),
	trainingDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("training_delete", { id })),
	trainingAddParticipant: (trainingId: number, employeeId: number) => typedError<number, string>(__TAURI_INVOKE("training_add_participant", { trainingId, employeeId })),
	trainingParticipantStatus: (participantId: number, status: string) => typedError<null, string>(__TAURI_INVOKE("training_participant_status", { participantId, status })),
	trainingCertifications: () => typedError<Certification[], string>(__TAURI_INVOKE("training_certifications")),
	trainingCertificationAdd: (input: CertificationInput) => typedError<number, string>(__TAURI_INVOKE("training_certification_add", { input })),
	trainingMaterials: (trainingId: number) => typedError<Material[], string>(__TAURI_INVOKE("training_materials", { trainingId })),
	trainingMaterialAdd: (trainingId: number, title: string, kind: string, url: string | null) => typedError<number, string>(__TAURI_INVOKE("training_material_add", { trainingId, title, kind, url })),
	trainingMaterialDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("training_material_delete", { id })),
	trainingQuizScore: (participantId: number, score: number | null) => typedError<null, string>(__TAURI_INVOKE("training_quiz_score", { participantId, score })),
	trainingSkillMatrix: () => typedError<SkillCell[], string>(__TAURI_INVOKE("training_skill_matrix")),
	trainingSkillSet: (employeeId: number, skillName: string, level: number) => typedError<null, string>(__TAURI_INVOKE("training_skill_set", { employeeId, skillName, level })),
	assetCategories: () => typedError<Category[], string>(__TAURI_INVOKE("asset_categories")),
	assetCategorySave: (id: number | null, code: string, name: string) => typedError<number, string>(__TAURI_INVOKE("asset_category_save", { id, code, name })),
	assetCategoryDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("asset_category_delete", { id })),
	assetsList: (search: string) => typedError<Asset[], string>(__TAURI_INVOKE("assets_list", { search })),
	assetDetail: (id: number) => typedError<{
	asset: Asset,
	assignments: AssetAssignment[],
	maintenance: Maintenance[],
} | null, string>(__TAURI_INVOKE("asset_detail", { id })),
	assetSave: (id: number | null, input: AssetInput) => typedError<number, string>(__TAURI_INVOKE("asset_save", { id, input })),
	assetDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("asset_delete", { id })),
	assetMy: () => typedError<MyAsset[], string>(__TAURI_INVOKE("asset_my")),
	assetAssign: (assetId: number, input: AssignInput) => typedError<number, string>(__TAURI_INVOKE("asset_assign", { assetId, input })),
	assetReturn: (assignmentId: number, input: ReturnInput) => typedError<null, string>(__TAURI_INVOKE("asset_return", { assignmentId, input })),
	assetMaintenanceAdd: (assetId: number, input: MaintenanceInput) => typedError<number, string>(__TAURI_INVOKE("asset_maintenance_add", { assetId, input })),
	assetMarkAvailable: (assetId: number) => typedError<null, string>(__TAURI_INVOKE("asset_mark_available", { assetId })),
	tripMy: () => typedError<Trip[], string>(__TAURI_INVOKE("trip_my")),
	tripAll: () => typedError<Trip[], string>(__TAURI_INVOKE("trip_all")),
	tripPending: () => typedError<Trip[], string>(__TAURI_INVOKE("trip_pending")),
	tripExpenses: (tripId: number) => typedError<TripExpense[], string>(__TAURI_INVOKE("trip_expenses", { tripId })),
	tripCreate: (input: TripInput) => typedError<number, string>(__TAURI_INVOKE("trip_create", { input })),
	tripDecide: (id: number, decision: string) => typedError<null, string>(__TAURI_INVOKE("trip_decide", { id, decision })),
	tripExpenseAdd: (tripId: number, input: TripExpenseInput, receipt: {
	name: string,
	mime: string,
	bytes: number[],
} | null) => typedError<number, string>(__TAURI_INVOKE("trip_expense_add", { tripId, input, receipt })),
	tripSettle: (tripId: number) => typedError<null, string>(__TAURI_INVOKE("trip_settle", { tripId })),
	reimburseCategories: () => typedError<ReimburseCategory[], string>(__TAURI_INVOKE("reimburse_categories")),
	reimburseCategorySave: (id: number | null, code: string, name: string, maxAmount: number | null) => typedError<number, string>(__TAURI_INVOKE("reimburse_category_save", { id, code, name, maxAmount })),
	reimburseCategoryDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("reimburse_category_delete", { id })),
	reimburseMy: () => typedError<Reimburse[], string>(__TAURI_INVOKE("reimburse_my")),
	reimburseAll: () => typedError<Reimburse[], string>(__TAURI_INVOKE("reimburse_all")),
	reimburseCreate: (input: ReimburseInput, receipt: {
	name: string,
	mime: string,
	bytes: number[],
} | null) => typedError<number, string>(__TAURI_INVOKE("reimburse_create", { input, receipt })),
	reimburseDecide: (id: number, action: string) => typedError<string, string>(__TAURI_INVOKE("reimburse_decide", { id, action })),
	dashboardHr: () => typedError<HrDashboard, string>(__TAURI_INVOKE("dashboard_hr")),
	dashboardMe: () => typedError<MySummary, string>(__TAURI_INVOKE("dashboard_me")),
	notificationRecent: () => typedError<Notification[], string>(__TAURI_INVOKE("notification_recent")),
	notificationAll: () => typedError<Notification[], string>(__TAURI_INVOKE("notification_all")),
	notificationUnread: () => typedError<number, string>(__TAURI_INVOKE("notification_unread")),
	notificationMarkRead: (id: number) => typedError<null, string>(__TAURI_INVOKE("notification_mark_read", { id })),
	notificationMarkAll: () => typedError<null, string>(__TAURI_INVOKE("notification_mark_all")),
	announcementVisible: () => typedError<Announcement[], string>(__TAURI_INVOKE("announcement_visible")),
	announcementList: () => typedError<Announcement[], string>(__TAURI_INVOKE("announcement_list")),
	announcementGet: (id: number) => typedError<Announcement, string>(__TAURI_INVOKE("announcement_get", { id })),
	announcementCreate: (input: AnnouncementInput) => typedError<number, string>(__TAURI_INVOKE("announcement_create", { input })),
	announcementDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("announcement_delete", { id })),
	reportEmployees: (search: string | null, departmentId: number | null, status: string | null) => typedError<ReportTable, string>(__TAURI_INVOKE("report_employees", { search, departmentId, status })),
	reportHeadcount: () => typedError<ReportTable, string>(__TAURI_INVOKE("report_headcount")),
	reportAttendance: (month: string, departmentId: number | null) => typedError<ReportTable, string>(__TAURI_INVOKE("report_attendance", { month, departmentId })),
	reportLeave: (year: number) => typedError<ReportTable, string>(__TAURI_INVOKE("report_leave", { year })),
	reportPayroll: (periodId: number) => typedError<ReportTable, string>(__TAURI_INVOKE("report_payroll", { periodId })),
	reportPph21Annual: (year: number) => typedError<ReportTable, string>(__TAURI_INVOKE("report_pph21_annual", { year })),
	reportRecruitment: () => typedError<ReportTable, string>(__TAURI_INVOKE("report_recruitment")),
	reportPerformance: (periodId: number) => typedError<ReportTable, string>(__TAURI_INVOKE("report_performance", { periodId })),
	reportContracts: (before: string) => typedError<ReportTable, string>(__TAURI_INVOKE("report_contracts", { before })),
	reportAnalytics: () => typedError<DeptStat[], string>(__TAURI_INVOKE("report_analytics")),
	reportExport: (kind: string, format: string, arg1: string | null, arg2: number | null) => typedError<ExportFile, string>(__TAURI_INVOKE("report_export", { kind, format, arg1, arg2 })),
};

/* Types */
/**  Satu baris alamat. */
export type AddressRow = {
	address: string | null,
	city: string | null,
	province: string | null,
	postal_code: string | null,
};

/**  Pasangan alamat KTP dan domisili. */
export type Addresses = {
	ktp: AddressRow | null,
	domicile: AddressRow | null,
};

export type AnnounceLite = {
	id: number,
	title: string,
	created_at: string,
};

export type Announcement = {
	id: number,
	title: string,
	content: string,
	target_type: string,
	publish_at: string | null,
	expire_at: string | null,
	status: string,
	created_by_name: string | null,
	created_at: string,
	read_at: string | null,
	targets: Target[],
};

export type AnnouncementInput = {
	title: string,
	content: string,
	target_type: string,
	publish_at: string | null,
	expire_at: string | null,
	targets: TargetInput[],
};

export type Assessment = {
	id: number,
	assessment_name: string,
	score: number | null,
	notes: string | null,
};

export type AssessmentInput = {
	assessment_name: string,
	score: number | null,
	notes: string | null,
};

export type Asset = {
	id: number,
	asset_code: string,
	name: string,
	asset_category_id: number,
	category_name: string,
	brand: string | null,
	serial_number: string | null,
	purchase_date: string | null,
	purchase_price: number | null,
	condition_status: string,
	status: string,
};

export type AssetAssignment = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	assigned_date: string,
	returned_date: string | null,
	condition_on_assign: string | null,
	condition_on_return: string | null,
	notes: string | null,
};

export type AssetDetail = {
	asset: Asset,
	assignments: AssetAssignment[],
	maintenance: Maintenance[],
};

export type AssetInput = {
	asset_code: string,
	name: string,
	asset_category_id: number,
	brand: string | null,
	serial_number: string | null,
	purchase_date: string | null,
	purchase_price: number | null,
	condition_status: string,
	status: string,
};

export type AssignInput = {
	employee_id: number,
	assigned_date: string,
	condition_on_assign: string | null,
	notes: string | null,
};

export type Assignment = {
	id: number,
	employee_id: number,
	employee_name: string,
	work_schedule_id: number | null,
	schedule_name: string | null,
	shift_id: number | null,
	shift_name: string | null,
	date: string | null,
	start_date: string,
	end_date: string | null,
};

export type AssignmentInput = {
	employee_id: number,
	work_schedule_id: number | null,
	shift_id: number | null,
	date: string | null,
	start_date: string | null,
	end_date: string | null,
};

export type Attendance = {
	id: number,
	employee_id: number,
	date: string,
	clock_in: string | null,
	clock_out: string | null,
	status: string,
	late_minutes: number,
	early_minutes: number,
	work_minutes: number,
	notes: string | null,
	shift_id: number | null,
};

/**  Baris audit untuk daftar. */
export type AuditEntry = {
	id: number,
	user_id: number | null,
	action: string,
	module: string,
	record_id: string | null,
	description: string | null,
	created_at: string,
};

/**  Satu berkas cadangan. */
export type BackupFile = {
	name: string,
	size_bytes: number,
	modified_at: string,
};

export type Balance = {
	leave_type_id: number,
	code: string,
	name: string,
	is_paid: boolean,
	allocated_days: number | null,
	used_days: number | null,
	carried_days: number | null,
	adjustment_days: number | null,
	remaining: number | null,
};

export type Birthday = {
	name: string,
	employee_number: string,
	birth_date: string | null,
};

export type BranchNode = {
	id: number,
	name: string,
	departments: DepartmentNode[],
};

export type CalendarDay = {
	date: string,
	label: string,
	kind: string,
};

export type CandidateDetail = {
	id: number,
	vacancy_id: number,
	vacancy_title: string,
	full_name: string,
	email: string | null,
	phone: string | null,
	birth_date: string | null,
	gender: string | null,
	address: string | null,
	cv_path: string | null,
	source: string | null,
	stage: string,
	rating: number | null,
	notes: string | null,
	employee_id: number | null,
	documents: CandidateDoc[],
	interviews: Interview[],
	assessments: Assessment[],
	stage_history: StageEvent[],
};

export type CandidateDoc = {
	id: number,
	name: string,
	file_path: string,
	category: string | null,
};

export type CandidateInput = {
	full_name: string,
	email: string | null,
	phone: string | null,
	birth_date: string | null,
	gender: string | null,
	address: string | null,
	source: string | null,
};

export type CandidateRow = {
	id: number,
	full_name: string,
	email: string | null,
	phone: string | null,
	stage: string,
	rating: number | null,
	created_at: string,
};

export type Category = {
	id: number,
	code: string,
	name: string,
};

export type Certification = {
	id: number,
	employee_id: number,
	employee_name: string,
	name: string,
	issuer: string | null,
	certificate_number: string | null,
	issued_date: string | null,
	expiry_date: string | null,
};

export type CertificationInput = {
	employee_id: number,
	name: string,
	issuer: string | null,
	certificate_number: string | null,
	issued_date: string | null,
	expiry_date: string | null,
};

export type ChildField = {
	name: string,
	label: string,
	field_type: string,
	required: boolean,
	options: StaticOpt[] | null,
};

export type ChildMeta = {
	slug: string,
	title: string,
	fields: ChildField[],
};

export type ClearanceItem = {
	id: number,
	item_name: string,
	department: string | null,
	is_cleared: boolean,
	cleared_at: string | null,
	notes: string | null,
};

/**  Hasil clock in/out: status + pesan. */
export type ClockResult = {
	status: string,
	message: string,
};

/**  Profil perusahaan (baris pertama). */
export type Company = {
	id: number,
	code: string,
	name: string,
	legal_name: string | null,
	address: string | null,
	city: string | null,
	province: string | null,
	postal_code: string | null,
	phone: string | null,
	email: string | null,
	npwp: string | null,
	established_date: string | null,
};

/**  Pembaruan parsial profil perusahaan (field kosong = pertahankan nilai lama). */
export type CompanyInput = {
	name: string | null,
	legal_name: string | null,
	address: string | null,
	city: string | null,
	province: string | null,
	postal_code: string | null,
	phone: string | null,
	email: string | null,
	npwp: string | null,
	established_date: string | null,
};

export type CompanyNode = {
	id: number,
	name: string,
	employee_count: number,
	branches: BranchNode[],
};

export type Component = {
	id: number,
	code: string,
	name: string,
	component_type: string,
	calculation_type: string,
	is_taxable: boolean,
	is_active: boolean,
};

export type ComponentInput = {
	code: string,
	name: string,
	component_type: string,
	calculation_type: string,
	is_taxable: boolean,
	is_active: boolean,
};

/**
 *  Metadata tipe child untuk form dinamis.
 *  Kontrak aktif yang berakhir dalam N hari ke depan (untuk alert jatuh tempo).
 */
export type ContractAlert = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	contract_number: string,
	contract_type: string,
	end_date: string,
	days_left: number,
};

export type Correction = {
	id: number,
	employee_id: number,
	employee_name: string,
	date: string,
	requested_clock_in: string | null,
	requested_clock_out: string | null,
	reason: string,
	status: string,
	notes: string | null,
	created_at: string,
};

export type CorrectionInput = {
	date: string,
	requested_clock_in: string | null,
	requested_clock_out: string | null,
	reason: string,
};

/**  Status database untuk layar diagnosa. */
export type DbStatus = {
	ok: boolean,
	tables: number,
	users: number,
	data_dir: string,
};

export type Deduction = {
	id: number,
	employee_id: number,
	employee_name: string,
	deduction_type: string,
	description: string,
	amount: number | null,
	installment_no: number | null,
	total_installments: number | null,
	status: string,
};

export type DeductionInput = {
	employee_id: number,
	deduction_type: string,
	description: string,
	amount: number | null,
	installment_no: number | null,
	total_installments: number | null,
};

export type DepartmentNode = {
	id: number,
	name: string,
	head_name: string | null,
	employee_count: number,
	divisions: DivisionNode[],
};

export type DeptStat = {
	department: string,
	employees: number,
	open_vacancies: number,
	active_trainings: number,
	avg_performance: number | null,
};

/**  Node struktur untuk tampilan bagan. */
export type DivisionNode = {
	id: number,
	name: string,
};

/**  Dokumen karyawan. */
export type Document = {
	id: number,
	category: string,
	name: string,
	file_path: string,
	file_size: number | null,
	mime_type: string | null,
	expiry_date: string | null,
	created_at: string,
};

/**  Isi berkas untuk unduh/pratinjau. */
export type DocumentBytes = {
	mime: string,
	name: string,
	bytes: number[],
};

export type Dropdowns = {
	companies: NamedOpt[],
	branches: NamedOpt[],
	departments: NamedOpt[],
	divisions: NamedOpt[],
	sections: NamedOpt[],
	positions: NamedOpt[],
	job_levels: NamedOpt[],
	job_grades: NamedOpt[],
	work_locations: NamedOpt[],
	cost_centers: NamedOpt[],
	employees: NamedOpt[],
};

/**  Detail penuh + label relasi. */
export type EmployeeDetail = {
	id: number,
	employee_number: string,
	nik: string | null,
	first_name: string,
	last_name: string | null,
	photo: string | null,
	birth_place: string | null,
	birth_date: string | null,
	gender: string,
	religion: string | null,
	marital_status: string,
	phone: string | null,
	personal_email: string | null,
	company_id: number,
	branch_id: number | null,
	department_id: number | null,
	division_id: number | null,
	section_id: number | null,
	position_id: number | null,
	job_level_id: number | null,
	job_grade_id: number | null,
	work_location_id: number | null,
	cost_center_id: number | null,
	supervisor_id: number | null,
	manager_id: number | null,
	join_date: string,
	appointment_date: string | null,
	resign_date: string | null,
	employment_status: string,
	employment_type: string,
	bank_name: string | null,
	bank_account_number: string | null,
	bank_account_holder: string | null,
	npwp: string | null,
	ptkp_status: string | null,
	bpjs_health_number: string | null,
	bpjs_employment_number: string | null,
	company_name: string | null,
	branch_name: string | null,
	department_name: string | null,
	division_name: string | null,
	section_name: string | null,
	position_name: string | null,
	job_level_name: string | null,
	job_grade_name: string | null,
	work_location_name: string | null,
	cost_center_name: string | null,
	supervisor_name: string | null,
	manager_name: string | null,
};

/**  Filter daftar. */
export type EmployeeFilter = {
	department_id: number | null,
	position_id: number | null,
	branch_id: number | null,
	employment_status: string | null,
	gender: string | null,
	employment_type: string | null,
};

/**  Input form karyawan. */
export type EmployeeInput = {
	nik: string | null,
	first_name: string,
	last_name: string | null,
	gender: string,
	birth_place: string | null,
	birth_date: string | null,
	religion: string | null,
	marital_status: string,
	phone: string | null,
	personal_email: string | null,
	company_id: number,
	branch_id: number | null,
	department_id: number | null,
	division_id: number | null,
	section_id: number | null,
	position_id: number | null,
	job_level_id: number | null,
	job_grade_id: number | null,
	work_location_id: number | null,
	cost_center_id: number | null,
	supervisor_id: number | null,
	manager_id: number | null,
	join_date: string,
	appointment_date: string | null,
	employment_status: string,
	employment_type: string,
	bank_name: string | null,
	bank_account_number: string | null,
	bank_account_holder: string | null,
	npwp: string | null,
	ptkp_status: string | null,
	bpjs_health_number: string | null,
	bpjs_employment_number: string | null,
};

export type EmployeePage = {
	rows: EmployeeRow[],
	total: number,
};

/**  Baris daftar karyawan. */
export type EmployeeRow = {
	id: number,
	employee_number: string,
	first_name: string,
	last_name: string | null,
	photo: string | null,
	join_date: string,
	employment_status: string,
	employment_type: string,
	department_name: string | null,
	position_name: string | null,
};

/**  Metadata entitas untuk tab dan tabel. */
export type EntityMeta = {
	slug: string,
	title: string,
	columns: string[],
	fields: FieldMeta[],
};

export type ExitInterview = {
	feedback: string | null,
	reason_category: string | null,
	would_recommend: boolean | null,
	satisfaction_score: number | null,
};

export type ExitInterviewInput = {
	feedback: string | null,
	reason_category: string | null,
	would_recommend: boolean | null,
	satisfaction_score: number | null,
};

export type ExportFile = {
	filename: string,
	mime: string,
	bytes: number[],
};

/**  Metadata field untuk membangun form dinamis. */
export type FieldMeta = {
	name: string,
	label: string,
	field_type: string,
	required: boolean,
	options: Opt[] | null,
};

/**  Berkas dari frontend (dibaca via input file, ditulis Rust ke data dir). */
export type FileUpload = {
	name: string,
	mime: string,
	bytes: number[],
};

export type Holiday = {
	id: number,
	name: string,
	date: string,
	holiday_type: string,
	description: string | null,
};

export type HolidayInput = {
	name: string,
	date: string,
	holiday_type: string,
	description: string | null,
};

export type HolidayLite = {
	name: string,
	date: string,
};

export type HrDashboard = {
	total_employees: number,
	new_hires_this_month: number,
	resigned_this_month: number,
	active_contracts: number,
	expiring_contracts: number,
	pending_leave: number,
	pending_overtime: number,
	pending_corrections: number,
	pending_trips: number,
	present_today: number,
	late_today: number,
	birthdays_today: Birthday[],
	upcoming_holidays: HolidayLite[],
	recent_announcements: AnnounceLite[],
	headcount_by_department: NameCount[],
	headcount_by_type: NameCount[],
};

export type Interview = {
	id: number,
	interviewer_id: number | null,
	interviewer_name: string | null,
	schedule_at: string,
	location: string | null,
	interview_type: string,
	result: string,
	notes: string | null,
};

export type InterviewInput = {
	interviewer_id: number | null,
	schedule_at: string,
	location: string | null,
	interview_type: string,
	notes: string | null,
};

export type Kpi = {
	id: number,
	name: string,
	description: string | null,
	department_id: number | null,
	department_name: string | null,
};

export type KpiInput = {
	name: string,
	description: string | null,
	department_id: number | null,
};

export type LeaveBalanceLite = {
	leave_type: string,
	allocated: number | null,
	used: number | null,
	remaining: number | null,
};

export type LeaveCreate = {
	leave_type_id: number,
	start_date: string,
	end_date: string,
	reason: string | null,
};

export type LeaveRequest = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	leave_type_id: number,
	leave_type_name: string,
	start_date: string,
	end_date: string,
	total_days: number | null,
	reason: string | null,
	status: string,
	current_step: number,
	created_at: string,
};

export type LeaveType = {
	id: number,
	code: string,
	name: string,
	default_days_per_year: number | null,
	is_paid: boolean,
	carry_forward: boolean,
	carry_forward_max_days: number | null,
	requires_attachment: boolean,
};

export type LeaveTypeInput = {
	code: string,
	name: string,
	default_days_per_year: number | null,
	is_paid: boolean,
	carry_forward: boolean,
	carry_forward_max_days: number | null,
	requires_attachment: boolean,
};

/**  Hasil login berhasil. */
export type LoginOk = {
	user: SessionUser,
	must_change_password: boolean,
	mfa_required: boolean,
};

export type Maintenance = {
	id: number,
	maintenance_date: string,
	description: string,
	cost: number | null,
	performed_by: string | null,
};

export type MaintenanceInput = {
	maintenance_date: string,
	description: string,
	cost: number | null,
	performed_by: string | null,
};

export type ManualInput = {
	employee_id: number,
	date: string,
	clock_in: string | null,
	clock_out: string | null,
	status: string,
	notes: string | null,
};

/**  Satu materi e-learning milik training. */
export type Material = {
	id: number,
	training_id: number,
	title: string,
	kind: string,
	url: string | null,
};

/**  Data enroll MFA untuk dipindai/diketik ke aplikasi authenticator. */
export type MfaSetup = {
	secret: string,
	otpauth_url: string,
};

export type MyAsset = {
	assignment_id: number,
	asset_code: string,
	name: string,
	brand: string | null,
	category_name: string,
	assigned_date: string,
};

export type MySummary = {
	employee_name: string,
	employee_number: string,
	department: string | null,
	position: string | null,
	today_status: string | null,
	today_clock_in: string | null,
	pending_leave: number,
	pending_overtime: number,
	pending_corrections: number,
	my_assets: number,
	unread_announcements: number,
	leave_balances: LeaveBalanceLite[],
};

export type NameCount = {
	name: string,
	count: number,
};

/**  Opsi dropdown form karyawan. */
export type NamedOpt = {
	id: number,
	name: string,
};

export type Notification = {
	id: number,
	kind: string,
	title: string,
	message: string | null,
	link: string | null,
	is_read: boolean,
	created_at: string,
};

export type OffboardingCreate = {
	resignation_date: string,
	last_working_date: string,
	reason: string | null,
};

export type OffboardingDetail = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	supervisor_id: number | null,
	resignation_date: string,
	last_working_date: string,
	reason: string | null,
	status: string,
	current_step: number,
	exit_interview: ExitInterview | null,
	clearance_items: ClearanceItem[],
};

export type OffboardingRow = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	resignation_date: string,
	last_working_date: string,
	status: string,
	current_step: number,
};

export type Onboarding = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	start_date: string,
	status: string,
	progress_percent: number,
	tasks: OnboardingTask[],
};

export type OnboardingTask = {
	id: number,
	task_name: string,
	is_completed: boolean,
	completed_at: string | null,
	sort_order: number,
};

/**  Opsi dropdown untuk field select. */
export type Opt = {
	id: number,
	name: string,
};

/**  Halaman daftar generik (nilai selalu string; frontend format ulang). */
export type OrgPage = {
	rows: { [key in string]: string }[],
	total: number,
};

export type Overtime = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	date: string,
	start_time: string,
	end_time: string,
	duration_minutes: number,
	reason: string | null,
	status: string,
	current_step: number,
	created_at: string,
};

export type OvertimeCreate = {
	date: string,
	start_time: string,
	end_time: string,
	reason: string | null,
};

export type Participant = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	status: string,
	quiz_score: number | null,
};

export type PayrollDetail = {
	id: number,
	employee_id: number,
	employee_number: string,
	name: string,
	department_name: string | null,
	position_name: string | null,
	period_name: string,
	start_date: string,
	end_date: string,
	basic_salary: number | null,
	total_income: number | null,
	total_deduction: number | null,
	net_salary: number | null,
	status: string,
	lines: PayrollLine[],
};

export type PayrollLine = {
	component_name: string,
	line_type: string,
	amount: number | null,
};

export type PayrollRow = {
	id: number,
	employee_id: number,
	employee_number: string,
	name: string,
	basic_salary: number | null,
	total_income: number | null,
	total_deduction: number | null,
	net_salary: number | null,
	status: string,
};

/**  Berkas slip untuk unduh. */
export type PayslipFile = {
	mime: string,
	name: string,
	bytes: number[],
};

export type PayslipInfo = {
	id: number,
	payroll_id: number,
	payslip_number: string,
	period_name: string,
	net_salary: number | null,
	pdf_ready: boolean,
};

export type PerfPeriod = {
	id: number,
	name: string,
	period_type: string,
	start_date: string,
	end_date: string,
	status: string,
};

export type PerfPeriodInput = {
	name: string,
	period_type: string,
	start_date: string,
	end_date: string,
	status: string,
};

export type Period = {
	id: number,
	name: string,
	start_date: string,
	end_date: string,
	payment_date: string | null,
	status: string,
	employee_count: number,
	total_net: number | null,
};

export type PeriodInput = {
	name: string,
	start_date: string,
	end_date: string,
	payment_date: string | null,
};

/**  Izin tunggal. */
export type Permission = {
	id: number,
	slug: string,
	name: string,
	module: string,
};

export type PermissionCreate = {
	permission_type_id: number,
	date: string,
	start_time: string | null,
	end_time: string | null,
	reason: string,
};

export type PermissionRequest = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	permission_type_id: number,
	permission_type_name: string,
	date: string,
	start_time: string | null,
	end_time: string | null,
	reason: string,
	status: string,
	created_at: string,
};

export type PermissionType = {
	id: number,
	code: string,
	name: string,
};

export type RecapRow = {
	employee_id: number,
	employee_number: string,
	name: string,
	department_name: string | null,
	clock_in: string | null,
	clock_out: string | null,
	status: string | null,
	late_minutes: number | null,
	work_minutes: number | null,
};

export type Reimburse = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	category_id: number,
	category_name: string,
	amount: number | null,
	description: string | null,
	receipt_path: string | null,
	status: string,
	current_step: number,
	paid_at: string | null,
	supervisor_id: number | null,
	manager_id: number | null,
};

export type ReimburseCategory = {
	id: number,
	code: string,
	name: string,
	max_amount: number | null,
};

export type ReimburseInput = {
	category_id: number,
	amount: number | null,
	description: string | null,
};

export type ReportTable = {
	title: string,
	headers: string[],
	rows: string[][],
};

export type ReturnInput = {
	returned_date: string,
	condition_on_return: string | null,
	notes: string | null,
};

export type ReviewDetail = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	period_name: string,
	status: string,
	self_score: number | null,
	supervisor_score: number | null,
	manager_score: number | null,
	hr_score: number | null,
	final_score: number | null,
	final_rating: number | null,
	kpis: ReviewKpi[],
	scores: ReviewScore[],
};

export type ReviewKpi = {
	id: number,
	kpi_name: string,
	target: number | null,
	weight: number | null,
	actual: number | null,
	score: number | null,
};

export type ReviewRow = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	period_name: string,
	status: string,
	final_score: number | null,
	final_rating: number | null,
};

export type ReviewScore = {
	reviewer_role: string,
	reviewer_id: number | null,
	comments: string | null,
	rating: number | null,
};

/**  Peran untuk daftar dan form. */
export type Role = {
	id: number,
	slug: string,
	name: string,
	description: string | null,
	is_system: boolean,
	user_count: number,
};

/**  Komponen gaji terpasang + katalog. */
export type SalaryComponentRow = {
	id: number,
	code: string,
	name: string,
	component_type: string,
	amount: number | null,
};

/**  Baris gaji pokok. */
export type SalaryRow = {
	id: number,
	basic_salary: number | null,
	effective_date: string,
	is_active: boolean,
};

export type Schedule = {
	id: number,
	name: string,
	description: string | null,
	days: ScheduleDay[],
};

export type ScheduleDay = {
	day_of_week: number,
	day_name: string,
	shift_id: number | null,
	is_working_day: boolean,
};

export type ScheduleInput = {
	name: string,
	description: string | null,
};

/**  Pengguna yang sedang login. */
export type SessionUser = {
	id: number,
	username: string,
	must_change_password: boolean,
	is_super_admin: boolean,
	roles: string[],
	permissions: string[],
};

/**  Satu baris pengaturan. */
export type Setting = {
	key: string,
	value: string | null,
	group: string,
};

export type Shift = {
	id: number,
	name: string,
	start_time: string,
	end_time: string,
	break_start: string | null,
	break_end: string | null,
	grace_period_minutes: number,
	is_overnight: boolean,
};

export type ShiftInput = {
	name: string,
	start_time: string,
	end_time: string,
	break_start: string | null,
	break_end: string | null,
	grace_period_minutes: number,
	is_overnight: boolean,
};

export type SkillCell = {
	employee_id: number,
	employee_name: string,
	skill_name: string,
	level: number,
};

export type StageEvent = {
	stage: string,
	notes: string | null,
	changed_at: string,
};

/**  Opsi statis untuk form child. */
export type StaticOpt = {
	value: string,
	label: string,
};

export type Target = {
	target_type: string,
	target_id: number,
	target_name: string | null,
};

export type TargetInput = {
	target_type: string,
	target_id: number,
};

export type Training = {
	id: number,
	title: string,
	description: string | null,
	trainer_name: string | null,
	start_date: string,
	end_date: string,
	location: string | null,
	cost: number | null,
	quota: number | null,
	status: string,
	participant_count: number,
};

export type TrainingInput = {
	title: string,
	description: string | null,
	trainer_name: string | null,
	start_date: string,
	end_date: string,
	location: string | null,
	cost: number | null,
	quota: number | null,
	status: string,
};

export type Trip = {
	id: number,
	employee_id: number,
	employee_name: string,
	employee_number: string,
	destination: string,
	purpose: string,
	start_date: string,
	end_date: string,
	transportation: string | null,
	hotel: string | null,
	budget: number | null,
	status: string,
	current_step: number,
	expense_total: number | null,
};

export type TripExpense = {
	id: number,
	category: string,
	description: string | null,
	amount: number | null,
	receipt_path: string | null,
};

export type TripExpenseInput = {
	category: string,
	description: string | null,
	amount: number | null,
};

export type TripInput = {
	destination: string,
	purpose: string,
	start_date: string,
	end_date: string,
	transportation: string | null,
	hotel: string | null,
	budget: number | null,
};

/**  Baris pengguna untuk tabel admin. */
export type UserRow = {
	id: number,
	username: string,
	email: string,
	status: string,
	must_change_password: boolean,
	employee_name: string | null,
	roles: string[],
};

export type Vacancy = {
	id: number,
	title: string,
	department_id: number | null,
	department_name: string | null,
	position_id: number | null,
	position_name: string | null,
	employment_type: string,
	description: string | null,
	requirements: string | null,
	quota: number,
	status: string,
	posted_date: string | null,
	closing_date: string | null,
	candidate_count: number,
};

export type VacancyInput = {
	title: string,
	department_id: number | null,
	position_id: number | null,
	employment_type: string,
	description: string | null,
	requirements: string | null,
	quota: number,
	status: string,
	posted_date: string | null,
	closing_date: string | null,
};

/**  Alur beserta tahap-tahapnya. */
export type Workflow = {
	id: number,
	module: string,
	name: string,
	is_active: boolean,
	steps: WorkflowStep[],
};

/**  Satu tahap persetujuan. */
export type WorkflowStep = {
	id: number,
	step_order: number,
	approver_type: string,
	role_id: number | null,
	user_id: number | null,
	role_name: string | null,
	username: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

