// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	dbStatus: () => typedError<DbStatus, string>(__TAURI_INVOKE("db_status")),
	login: (username: string, password: string) => typedError<LoginOk, string>(__TAURI_INVOKE("login", { username, password })),
	logout: () => typedError<null, string>(__TAURI_INVOKE("logout")),
	sessionState: () => typedError<{
	id: number,
	username: string,
	must_change_password: boolean,
	is_super_admin: boolean,
	roles: string[],
	permissions: string[],
} | null, string>(__TAURI_INVOKE("session_state")),
	changePassword: (currentPassword: string, newPassword: string) => typedError<null, string>(__TAURI_INVOKE("change_password", { currentPassword, newPassword })),
	requestPasswordReset: (email: string) => typedError<string | null, string>(__TAURI_INVOKE("request_password_reset", { email })),
	resetPassword: (token: string, newPassword: string) => typedError<null, string>(__TAURI_INVOKE("reset_password", { token, newPassword })),
	listRoles: () => typedError<Role[], string>(__TAURI_INVOKE("list_roles")),
	createRole: (slug: string, name: string, description: string | null) => typedError<number, string>(__TAURI_INVOKE("create_role", { slug, name, description })),
	updateRole: (roleId: number, name: string, description: string | null) => typedError<null, string>(__TAURI_INVOKE("update_role", { roleId, name, description })),
	deleteRole: (roleId: number) => typedError<null, string>(__TAURI_INVOKE("delete_role", { roleId })),
	listPermissions: () => typedError<Permission[], string>(__TAURI_INVOKE("list_permissions")),
	rolePermissionIds: (roleId: number) => typedError<number[], string>(__TAURI_INVOKE("role_permission_ids", { roleId })),
	syncRolePermissions: (roleId: number, permissionIds: number[]) => typedError<null, string>(__TAURI_INVOKE("sync_role_permissions", { roleId, permissionIds })),
	listUsers: () => typedError<UserRow[], string>(__TAURI_INVOKE("list_users")),
	userRoleIds: (userId: number) => typedError<number[], string>(__TAURI_INVOKE("user_role_ids", { userId })),
	syncUserRoles: (userId: number, roleIds: number[]) => typedError<null, string>(__TAURI_INVOKE("sync_user_roles", { userId, roleIds })),
	toggleUserStatus: (userId: number, status: string) => typedError<null, string>(__TAURI_INVOKE("toggle_user_status", { userId, status })),
	adminResetPassword: (userId: number, newPassword: string) => typedError<null, string>(__TAURI_INVOKE("admin_reset_password", { userId, newPassword })),
	auditList: (module: string | null, limit: number | null) => typedError<AuditEntry[], string>(__TAURI_INVOKE("audit_list", { module, limit })),
	getSettings: () => typedError<Setting[], string>(__TAURI_INVOKE("get_settings")),
	saveSettings: (items: ([string, string])[]) => typedError<null, string>(__TAURI_INVOKE("save_settings", { items })),
	getCompany: () => typedError<{
	id: number,
	code: string,
	name: string,
	legal_name: string | null,
	address: string | null,
	city: string | null,
	province: string | null,
	postal_code: string | null,
	phone: string | null,
	email: string | null,
	npwp: string | null,
	established_date: string | null,
} | null, string>(__TAURI_INVOKE("get_company")),
	saveCompany: (input: CompanyInput) => typedError<null, string>(__TAURI_INVOKE("save_company", { input })),
	orgEntities: () => typedError<EntityMeta[], string>(__TAURI_INVOKE("org_entities")),
	orgList: (slug: string, search: string, page: number, perPage: number) => typedError<OrgPage, string>(__TAURI_INVOKE("org_list", { slug, search, page, perPage })),
	orgGet: (slug: string, id: number) => typedError<{ [key in string]: string } | null, string>(__TAURI_INVOKE("org_get", { slug, id })),
	orgOptions: (slug: string, field: string) => typedError<Opt[], string>(__TAURI_INVOKE("org_options", { slug, field })),
	orgSave: (slug: string, id: number | null, values: { [key in string]: string }) => typedError<number, string>(__TAURI_INVOKE("org_save", { slug, id, values })),
	orgDelete: (slug: string, id: number) => typedError<null, string>(__TAURI_INVOKE("org_delete", { slug, id })),
	orgChart: () => typedError<CompanyNode[], string>(__TAURI_INVOKE("org_chart")),
	listWorkflows: () => typedError<Workflow[], string>(__TAURI_INVOKE("list_workflows")),
	addWorkflowStep: (workflowId: number, approverType: string, roleId: number | null, userId: number | null) => typedError<number, string>(__TAURI_INVOKE("add_workflow_step", { workflowId, approverType, roleId, userId })),
	removeWorkflowStep: (stepId: number) => typedError<null, string>(__TAURI_INVOKE("remove_workflow_step", { stepId })),
	employeeList: (search: string, filters: EmployeeFilter, page: number, perPage: number) => typedError<EmployeePage, string>(__TAURI_INVOKE("employee_list", { search, filters, page, perPage })),
	employeeDetail: (id: number) => typedError<{
	id: number,
	employee_number: string,
	nik: string | null,
	first_name: string,
	last_name: string | null,
	photo: string | null,
	birth_place: string | null,
	birth_date: string | null,
	gender: string,
	religion: string | null,
	marital_status: string,
	phone: string | null,
	personal_email: string | null,
	company_id: number,
	branch_id: number | null,
	department_id: number | null,
	division_id: number | null,
	section_id: number | null,
	position_id: number | null,
	job_level_id: number | null,
	job_grade_id: number | null,
	work_location_id: number | null,
	cost_center_id: number | null,
	supervisor_id: number | null,
	manager_id: number | null,
	join_date: string,
	appointment_date: string | null,
	resign_date: string | null,
	employment_status: string,
	employment_type: string,
	bank_name: string | null,
	bank_account_number: string | null,
	bank_account_holder: string | null,
	npwp: string | null,
	ptkp_status: string | null,
	bpjs_health_number: string | null,
	bpjs_employment_number: string | null,
	company_name: string | null,
	branch_name: string | null,
	department_name: string | null,
	division_name: string | null,
	section_name: string | null,
	position_name: string | null,
	job_level_name: string | null,
	job_grade_name: string | null,
	work_location_name: string | null,
	cost_center_name: string | null,
	supervisor_name: string | null,
	manager_name: string | null,
} | null, string>(__TAURI_INVOKE("employee_detail", { id })),
	employeeDropdowns: () => typedError<Dropdowns, string>(__TAURI_INVOKE("employee_dropdowns")),
	employeeCreate: (input: EmployeeInput, photo: {
	name: string,
	mime: string,
	bytes: number[],
} | null) => typedError<number, string>(__TAURI_INVOKE("employee_create", { input, photo })),
	employeeUpdate: (id: number, input: EmployeeInput, resignDate: string | null, photo: {
	name: string,
	mime: string,
	bytes: number[],
} | null) => typedError<null, string>(__TAURI_INVOKE("employee_update", { id, input, resignDate, photo })),
	employeeDelete: (id: number) => typedError<null, string>(__TAURI_INVOKE("employee_delete", { id })),
	employeeChildTypes: () => typedError<ChildMeta[], string>(__TAURI_INVOKE("employee_child_types")),
	employeeChildList: (child: string, employeeId: number) => typedError<{ [key in string]: string }[], string>(__TAURI_INVOKE("employee_child_list", { child, employeeId })),
	employeeChildSave: (child: string, employeeId: number, id: number | null, values: { [key in string]: string }) => typedError<number, string>(__TAURI_INVOKE("employee_child_save", { child, employeeId, id, values })),
	employeeChildDelete: (child: string, employeeId: number, id: number) => typedError<null, string>(__TAURI_INVOKE("employee_child_delete", { child, employeeId, id })),
	employeeAddresses: (employeeId: number) => typedError<Addresses, string>(__TAURI_INVOKE("employee_addresses", { employeeId })),
	employeeAddressSave: (employeeId: number, addressType: string, values: { [key in string]: string }) => typedError<null, string>(__TAURI_INVOKE("employee_address_save", { employeeId, addressType, values })),
	employeeDocuments: (employeeId: number) => typedError<Document[], string>(__TAURI_INVOKE("employee_documents", { employeeId })),
	employeeDocumentUpload: (employeeId: number, category: string, name: string, expiryDate: string | null, file: FileUpload) => typedError<number, string>(__TAURI_INVOKE("employee_document_upload", { employeeId, category, name, expiryDate, file })),
	employeeDocumentBytes: (employeeId: number, id: number) => typedError<DocumentBytes, string>(__TAURI_INVOKE("employee_document_bytes", { employeeId, id })),
	employeeDocumentDelete: (employeeId: number, id: number) => typedError<null, string>(__TAURI_INVOKE("employee_document_delete", { employeeId, id })),
	employeeSalaryCurrent: (employeeId: number) => typedError<{
	id: number,
	basic_salary: number | null,
	effective_date: string,
	is_active: boolean,
} | null, string>(__TAURI_INVOKE("employee_salary_current", { employeeId })),
	employeeSalaryHistory: (employeeId: number) => typedError<SalaryRow[], string>(__TAURI_INVOKE("employee_salary_history", { employeeId })),
	employeeSalaryComponents: (salaryId: number) => typedError<SalaryComponentRow[], string>(__TAURI_INVOKE("employee_salary_components", { salaryId })),
	employeeAvailableComponents: () => typedError<SalaryComponentRow[], string>(__TAURI_INVOKE("employee_available_components")),
	employeeSetSalary: (employeeId: number, basicSalary: number | null, effectiveDate: string, components: ([number, number | null])[]) => typedError<number, string>(__TAURI_INVOKE("employee_set_salary", { employeeId, basicSalary, effectiveDate, components })),
};

/* Types */
/**  Satu baris alamat. */
export type AddressRow = {
	address: string | null,
	city: string | null,
	province: string | null,
	postal_code: string | null,
};

/**  Pasangan alamat KTP dan domisili. */
export type Addresses = {
	ktp: AddressRow | null,
	domicile: AddressRow | null,
};

/**  Baris audit untuk daftar. */
export type AuditEntry = {
	id: number,
	user_id: number | null,
	action: string,
	module: string,
	record_id: string | null,
	description: string | null,
	created_at: string,
};

export type BranchNode = {
	id: number,
	name: string,
	departments: DepartmentNode[],
};

export type ChildField = {
	name: string,
	label: string,
	field_type: string,
	required: boolean,
	options: StaticOpt[] | null,
};

export type ChildMeta = {
	slug: string,
	title: string,
	fields: ChildField[],
};

/**  Profil perusahaan (baris pertama). */
export type Company = {
	id: number,
	code: string,
	name: string,
	legal_name: string | null,
	address: string | null,
	city: string | null,
	province: string | null,
	postal_code: string | null,
	phone: string | null,
	email: string | null,
	npwp: string | null,
	established_date: string | null,
};

/**  Pembaruan parsial profil perusahaan (field kosong = pertahankan nilai lama). */
export type CompanyInput = {
	name: string | null,
	legal_name: string | null,
	address: string | null,
	city: string | null,
	province: string | null,
	postal_code: string | null,
	phone: string | null,
	email: string | null,
	npwp: string | null,
	established_date: string | null,
};

export type CompanyNode = {
	id: number,
	name: string,
	employee_count: number,
	branches: BranchNode[],
};

/**  Status database untuk layar diagnosa. */
export type DbStatus = {
	ok: boolean,
	tables: number,
	users: number,
	data_dir: string,
};

export type DepartmentNode = {
	id: number,
	name: string,
	head_name: string | null,
	employee_count: number,
	divisions: DivisionNode[],
};

/**  Node struktur untuk tampilan bagan. */
export type DivisionNode = {
	id: number,
	name: string,
};

/**  Dokumen karyawan. */
export type Document = {
	id: number,
	category: string,
	name: string,
	file_path: string,
	file_size: number | null,
	mime_type: string | null,
	expiry_date: string | null,
	created_at: string,
};

/**  Isi berkas untuk unduh/pratinjau. */
export type DocumentBytes = {
	mime: string,
	name: string,
	bytes: number[],
};

export type Dropdowns = {
	companies: NamedOpt[],
	branches: NamedOpt[],
	departments: NamedOpt[],
	divisions: NamedOpt[],
	sections: NamedOpt[],
	positions: NamedOpt[],
	job_levels: NamedOpt[],
	job_grades: NamedOpt[],
	work_locations: NamedOpt[],
	cost_centers: NamedOpt[],
	employees: NamedOpt[],
};

/**  Detail penuh + label relasi. */
export type EmployeeDetail = {
	id: number,
	employee_number: string,
	nik: string | null,
	first_name: string,
	last_name: string | null,
	photo: string | null,
	birth_place: string | null,
	birth_date: string | null,
	gender: string,
	religion: string | null,
	marital_status: string,
	phone: string | null,
	personal_email: string | null,
	company_id: number,
	branch_id: number | null,
	department_id: number | null,
	division_id: number | null,
	section_id: number | null,
	position_id: number | null,
	job_level_id: number | null,
	job_grade_id: number | null,
	work_location_id: number | null,
	cost_center_id: number | null,
	supervisor_id: number | null,
	manager_id: number | null,
	join_date: string,
	appointment_date: string | null,
	resign_date: string | null,
	employment_status: string,
	employment_type: string,
	bank_name: string | null,
	bank_account_number: string | null,
	bank_account_holder: string | null,
	npwp: string | null,
	ptkp_status: string | null,
	bpjs_health_number: string | null,
	bpjs_employment_number: string | null,
	company_name: string | null,
	branch_name: string | null,
	department_name: string | null,
	division_name: string | null,
	section_name: string | null,
	position_name: string | null,
	job_level_name: string | null,
	job_grade_name: string | null,
	work_location_name: string | null,
	cost_center_name: string | null,
	supervisor_name: string | null,
	manager_name: string | null,
};

/**  Filter daftar. */
export type EmployeeFilter = {
	department_id: number | null,
	position_id: number | null,
	branch_id: number | null,
	employment_status: string | null,
	gender: string | null,
	employment_type: string | null,
};

/**  Input form karyawan. */
export type EmployeeInput = {
	nik: string | null,
	first_name: string,
	last_name: string | null,
	gender: string,
	birth_place: string | null,
	birth_date: string | null,
	religion: string | null,
	marital_status: string,
	phone: string | null,
	personal_email: string | null,
	company_id: number,
	branch_id: number | null,
	department_id: number | null,
	division_id: number | null,
	section_id: number | null,
	position_id: number | null,
	job_level_id: number | null,
	job_grade_id: number | null,
	work_location_id: number | null,
	cost_center_id: number | null,
	supervisor_id: number | null,
	manager_id: number | null,
	join_date: string,
	appointment_date: string | null,
	employment_status: string,
	employment_type: string,
	bank_name: string | null,
	bank_account_number: string | null,
	bank_account_holder: string | null,
	npwp: string | null,
	ptkp_status: string | null,
	bpjs_health_number: string | null,
	bpjs_employment_number: string | null,
};

export type EmployeePage = {
	rows: EmployeeRow[],
	total: number,
};

/**  Baris daftar karyawan. */
export type EmployeeRow = {
	id: number,
	employee_number: string,
	first_name: string,
	last_name: string | null,
	photo: string | null,
	join_date: string,
	employment_status: string,
	employment_type: string,
	department_name: string | null,
	position_name: string | null,
};

/**  Metadata entitas untuk tab dan tabel. */
export type EntityMeta = {
	slug: string,
	title: string,
	columns: string[],
	fields: FieldMeta[],
};

/**  Metadata field untuk membangun form dinamis. */
export type FieldMeta = {
	name: string,
	label: string,
	field_type: string,
	required: boolean,
	options: Opt[] | null,
};

/**  Berkas dari frontend (dibaca via input file, ditulis Rust ke data dir). */
export type FileUpload = {
	name: string,
	mime: string,
	bytes: number[],
};

/**  Hasil login berhasil. */
export type LoginOk = {
	user: SessionUser,
	must_change_password: boolean,
};

/**  Opsi dropdown form karyawan. */
export type NamedOpt = {
	id: number,
	name: string,
};

/**  Opsi dropdown untuk field select. */
export type Opt = {
	id: number,
	name: string,
};

/**  Halaman daftar generik (nilai selalu string; frontend format ulang). */
export type OrgPage = {
	rows: { [key in string]: string }[],
	total: number,
};

/**  Izin tunggal. */
export type Permission = {
	id: number,
	slug: string,
	name: string,
	module: string,
};

/**  Peran untuk daftar dan form. */
export type Role = {
	id: number,
	slug: string,
	name: string,
	description: string | null,
	is_system: boolean,
	user_count: number,
};

/**  Komponen gaji terpasang + katalog. */
export type SalaryComponentRow = {
	id: number,
	code: string,
	name: string,
	component_type: string,
	amount: number | null,
};

/**  Baris gaji pokok. */
export type SalaryRow = {
	id: number,
	basic_salary: number | null,
	effective_date: string,
	is_active: boolean,
};

/**  Pengguna yang sedang login. */
export type SessionUser = {
	id: number,
	username: string,
	must_change_password: boolean,
	is_super_admin: boolean,
	roles: string[],
	permissions: string[],
};

/**  Satu baris pengaturan. */
export type Setting = {
	key: string,
	value: string | null,
	group: string,
};

/**  Opsi statis untuk form child. */
export type StaticOpt = {
	value: string,
	label: string,
};

/**  Baris pengguna untuk tabel admin. */
export type UserRow = {
	id: number,
	username: string,
	email: string,
	status: string,
	must_change_password: boolean,
	employee_name: string | null,
	roles: string[],
};

/**  Alur beserta tahap-tahapnya. */
export type Workflow = {
	id: number,
	module: string,
	name: string,
	is_active: boolean,
	steps: WorkflowStep[],
};

/**  Satu tahap persetujuan. */
export type WorkflowStep = {
	id: number,
	step_order: number,
	approver_type: string,
	role_id: number | null,
	user_id: number | null,
	role_name: string | null,
	username: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

